# Generated by Django 5.2.3 on 2025-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_hash', models.CharField(max_length=20, unique=True)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('student_no', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_no', models.CharField(max_length=15)),
            ],
        ),
    ]
