# Generated by Django 5.2.3 on 2025-07-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lateEntry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='barcode_hash',
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
