# Generated by Django 5.2.3 on 2025-07-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lateEntry', '0002_remove_student_barcode_hash_student_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_arrivals', to='lateEntry.student', to_field='roll_no')),
            ],
        ),
    ]
