# Generated by Django 5.2.3 on 2025-07-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lateEntry', '0003_latearrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('late_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lateEntry.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
